CREATE TABLE IF NOT EXISTS papas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  cedula VARCHAR(50) NOT NULL UNIQUE,
  fecha_nacimiento DATE NOT NULL,
  telefono VARCHAR(50),
  biometric_id VARCHAR(50),
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_papas_nombre ON papas(nombre);
CREATE UNIQUE INDEX IF NOT EXISTS uk_papas_biometric_id ON papas(biometric_id) WHERE biometric_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS asistencia_papa (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_papa INTEGER NOT NULL,
  fecha DATE NOT NULL,
  hora_entrada TIME,
  hora_salida TIME,
  observacion VARCHAR(500),
  CONSTRAINT fk_asistencia_papa FOREIGN KEY (id_papa) REFERENCES papas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_asistencia_papa_fecha ON asistencia_papa(fecha);
CREATE INDEX IF NOT EXISTS idx_asistencia_papa_id_papa_fecha ON asistencia_papa(id_papa, fecha);
