CREATE TABLE IF NOT EXISTS papa_plan (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_papa INTEGER NOT NULL,
  tipo VARCHAR(10) NOT NULL,
  id_servicio INTEGER NULL,
  id_paquete INTEGER NULL,
  total_sesiones INTEGER NOT NULL DEFAULT 1,
  sesiones_consumidas INTEGER NOT NULL DEFAULT 0,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NULL,
  CONSTRAINT ck_papa_plan_tipo CHECK (tipo IN ('SERVICIO','PAQUETE')),
  CONSTRAINT fk_papa_plan_papa FOREIGN KEY (id_papa) REFERENCES papas(id) ON DELETE CASCADE,
  CONSTRAINT fk_papa_plan_servicio FOREIGN KEY (id_servicio) REFERENCES servicios(id) ON DELETE SET NULL,
  CONSTRAINT fk_papa_plan_paquete FOREIGN KEY (id_paquete) REFERENCES paquetes(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_papa_plan_vigencia ON papa_plan(fecha_inicio, fecha_fin);
