CREATE TABLE IF NOT EXISTS acudientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  telefono VARCHAR(50),
  cc VARCHAR(50)
);
CREATE INDEX IF NOT EXISTS idx_acudientes_nombre ON acudientes(nombre);

CREATE TABLE IF NOT EXISTS ninos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  ti VARCHAR(50),
  fecha_nacimiento DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ninos_nombre ON ninos(nombre);

CREATE TABLE IF NOT EXISTS nino_acudiente (
  id_nino INTEGER NOT NULL,
  id_acudiente INTEGER NOT NULL,
  parentesco VARCHAR(50) NOT NULL DEFAULT 'acudiente',
  PRIMARY KEY (id_nino, id_acudiente),
  CONSTRAINT fk_nino_acudiente_nino FOREIGN KEY (id_nino) REFERENCES ninos(id) ON DELETE CASCADE,
  CONSTRAINT fk_nino_acudiente_acudiente FOREIGN KEY (id_acudiente) REFERENCES acudientes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS servicios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  precio NUMERIC(12,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_servicios_nombre ON servicios(nombre);

CREATE TABLE IF NOT EXISTS paquetes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  precio NUMERIC(12,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_paquetes_nombre ON paquetes(nombre);

CREATE TABLE IF NOT EXISTS paquete_servicio (
  id_paquete INTEGER NOT NULL,
  id_servicio INTEGER NOT NULL,
  PRIMARY KEY (id_paquete, id_servicio),
  CONSTRAINT fk_paquete_servicio_paquete FOREIGN KEY (id_paquete) REFERENCES paquetes(id) ON DELETE CASCADE,
  CONSTRAINT fk_paquete_servicio_servicio FOREIGN KEY (id_servicio) REFERENCES servicios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS nino_plan (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_nino INTEGER NOT NULL,
  tipo VARCHAR(10) NOT NULL,
  id_servicio INTEGER NULL,
  id_paquete INTEGER NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  CONSTRAINT ck_nino_plan_tipo CHECK (tipo IN ('SERVICIO','PAQUETE')),
  CONSTRAINT fk_nino_plan_nino FOREIGN KEY (id_nino) REFERENCES ninos(id) ON DELETE CASCADE,
  CONSTRAINT fk_nino_plan_servicio FOREIGN KEY (id_servicio) REFERENCES servicios(id) ON DELETE SET NULL,
  CONSTRAINT fk_nino_plan_paquete FOREIGN KEY (id_paquete) REFERENCES paquetes(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_nino_plan_vigencia ON nino_plan(fecha_inicio, fecha_fin);

CREATE TABLE IF NOT EXISTS asistencia (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_nino INTEGER NOT NULL,
  fecha DATE NOT NULL,
  hora_entrada TIME,
  hora_salida TIME,
  observacion VARCHAR(500),
  CONSTRAINT fk_asistencia_nino FOREIGN KEY (id_nino) REFERENCES ninos(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_asistencia_fecha ON asistencia(fecha);
CREATE UNIQUE INDEX IF NOT EXISTS uk_asistencia_nino_fecha ON asistencia(id_nino, fecha);
