CREATE TABLE IF NOT EXISTS grupos (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    color VARCHAR(7) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_grupos_nombre_lower ON grupos (LOWER(nombre));

INSERT INTO grupos (nombre, color)
SELECT 'APRENDER JUGANDO', '#3B82F6'
WHERE NOT EXISTS (SELECT 1 FROM grupos WHERE LOWER(nombre) = LOWER('APRENDER JUGANDO'));

INSERT INTO grupos (nombre, color)
SELECT 'ESTIMULACION Y NURODESARROLLO', '#A855F7'
WHERE NOT EXISTS (SELECT 1 FROM grupos WHERE LOWER(nombre) = LOWER('ESTIMULACION Y NURODESARROLLO'));

INSERT INTO grupos (nombre, color)
SELECT 'CLASES EXTRACURRICULARES', '#F59E0B'
WHERE NOT EXISTS (SELECT 1 FROM grupos WHERE LOWER(nombre) = LOWER('CLASES EXTRACURRICULARES'));
