CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Admin por defecto: entrelazados2026 / entrelazados2026*  (BCrypt 10 rounds)
INSERT INTO users (username, password_hash, nombre, role)
VALUES ('entrelazados2026', '$2a$10$aQwMXW7Kw2SvIMuGjFkFyO1iwy5c3EZgxV8iMeXX4RmDZ9Xzn9R/.', 'Administrador Principal', 'ADMIN')
ON CONFLICT (username) DO NOTHING;
